apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
      metadata:
        labels: 
          app: "goserver"
      spec:
        containers:
        - name: "goserver"
          image: nilsonrsvieira/hello-go:v5.4
          resources:
            requests: # Minimo para Rodar
             cpu: 100m
             memory: 20Mi
            limits:
              cpu: 500m
              memory: 25Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 3
            failureThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
          volumeMounts:
            - mountPath: "/go/src/goapp/myfamily"
              name: config
            - mountPath: "/go/pvc"
              name: goserver-volume
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 8080
        volumes:
          - name: goserver-volume
            persistentVolumeClaim:
              claimName: goserver-pvc
          - name: config
            configMap:
              name: configmap-family
              items:
              - key: members
                path: family.txt