apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 1
  template:
      metadata:
        labels: 
          app: "goserver"
      spec:
        containers:
        - name: "goserver"
          image: nilsonrsvieira/hello-go:v4
          # env:
          #   - name: NAME
          #     value: "Nilson Vieira"
          #   - name: AGE
          #     value: "33"
          # env:
          #   - name: NAME
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: NAME
          #   - name: AGE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: goserver-env
          #         key: AGE
          envFrom:
            - configMapRef:
                name: goserver-env
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080